urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()

import authority
authority.autodiscover()

from bookmarks.feeds import BookmarkFeed
from bookmarks.models import BookmarkInstance
from microblogging.feeds import TweetFeedAll, TweetFeedUser, TweetFeedUserWithFriends
from microblogging.models import Tweet
from swaps.models import Offer
from tagging.models import TaggedItem
from wakawaka.models import WikiPage

from pinax.apps.account.openid_consumer import PinaxConsumer
from pinax.apps.blog.feeds import BlogFeedAll, BlogFeedUser
from pinax.apps.blog.models import Post
from pinax.apps.photos.models import Image
from pinax.apps.topics.models import Topic
from pinax.apps.tribes.models import Tribe


handler500 = "pinax.views.server_error"


tweets_feed_dict = {"feed_dict": {
    "all": TweetFeedAll,
    "only": TweetFeedUser,
    "with_friends": TweetFeedUserWithFriends,
}}

blogs_feed_dict = {"feed_dict": {
    "all": BlogFeedAll,
    "only": BlogFeedUser,
}}

bookmarks_feed_dict = {"feed_dict": {"": BookmarkFeed }}


urlpatterns = patterns("",
    url(r"^$", direct_to_template, {
        "template": "homepage.html",
    }, name="home"),
    url(r"^admin/invite_user/$", "pinax.apps.signup_codes.views.admin_invite_user", name="admin_invite_user"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^about/", include("about.urls")),
    url(r"^account/", include("pinax.apps.account.urls")),
    url(r"^openid/(.*)", PinaxConsumer()),
    url(r"^profiles/", include("pinax.apps.profiles.urls")),
    url(r"^bbauth/", include("pinax.apps.bbauth.urls")),
    url(r"^authsub/", include("pinax.apps.authsub.urls")),
    url(r"^blog/", include("pinax.apps.blog.urls")),
    url(r"^invitations/", include("friends_app.urls")),
    url(r"^notices/", include("notification.urls")),
    url(r"^messages/", include("messages.urls")),
    url(r"^announcements/", include("announcements.urls")),
    url(r"^tweets/", include("microblogging.urls")),
    url(r"^tribes/", include("pinax.apps.tribes.urls")),
    url(r"^comments/", include("threadedcomments.urls")),
    url(r"^i18n/", include("django.conf.urls.i18n")),
    url(r"^bookmarks/", include("bookmarks.urls")),
    url(r"^photos/", include("pinax.apps.photos.urls")),
    url(r"^avatar/", include("avatar.urls")),
    url(r"^swaps/", include("swaps.urls")),
    url(r"^flag/", include("flag.urls")),
    url(r"^locations/", include("locations.urls")),
    url(r"^feeds/tweets/(.*)/$", "django.contrib.syndication.views.feed", tweets_feed_dict),
    url(r"^feeds/posts/(.*)/$", "django.contrib.syndication.views.feed", blogs_feed_dict),
    url(r"^feeds/bookmarks/(.*)/?$", "django.contrib.syndication.views.feed", bookmarks_feed_dict),
    url(r'^characters/', include('characters.urls')),
    url(r'^chronicles/', include('chronicles.urls')),
    url(r'^authority/', include('authority.urls')),

)

## @@@ for now, we'll use friends_app to glue this stuff together

friends_photos_kwargs = {
    "template_name": "photos/friends_photos.html",
    "friends_objects_function": lambda users: Image.objects.filter(is_public=True, member__in=users),
}

friends_blogs_kwargs = {
    "template_name": "blog/friends_posts.html",
    "friends_objects_function": lambda users: Post.objects.filter(author__in=users),
}

friends_tweets_kwargs = {
    "template_name": "microblogging/friends_tweets.html",
    "friends_objects_function": lambda users: Tweet.objects.filter(sender_id__in=[user.id for user in users], sender_type__name="user"),
}

friends_bookmarks_kwargs = {
    "template_name": "bookmarks/friends_bookmarks.html",
    "friends_objects_function": lambda users: Bookmark.objects.filter(saved_instances__user__in=users),
    "extra_context": {
        "user_bookmarks": lambda request: Bookmark.objects.filter(saved_instances__user=request.user),
    },
}

urlpatterns += patterns("",
    url(r"^photos/friends_photos/$", "friends_app.views.friends_objects", kwargs=friends_photos_kwargs, name="friends_photos"),
    url(r"^blog/friends_blogs/$", "friends_app.views.friends_objects", kwargs=friends_blogs_kwargs, name="friends_blogs"),
    url(r"^tweets/friends_tweets/$", "friends_app.views.friends_objects", kwargs=friends_tweets_kwargs, name="friends_tweets"),
    url(r"^bookmarks/friends_bookmarks/$", "friends_app.views.friends_objects", kwargs=friends_bookmarks_kwargs, name="friends_bookmarks"),
)

tagged_models = (
    dict(title="Blog Posts",
        query=lambda tag : TaggedItem.objects.get_by_model(Post, tag).filter(status=2),
        content_template="pinax_tagging_ext/blogs.html",
    ),
    dict(title="Bookmarks",
        query=lambda tag : TaggedItem.objects.get_by_model(BookmarkInstance, tag),
        content_template="pinax_tagging_ext/bookmarks.html",
    ),
    dict(title="Photos",
        query=lambda tag: TaggedItem.objects.get_by_model(Image, tag).filter(safetylevel=1),
        content_template="pinax_tagging_ext/photos.html",
    ),
    dict(title="Swap Offers",
        query=lambda tag : TaggedItem.objects.get_by_model(Offer, tag),
    ),
    dict(title="Topics",
        query=lambda tag: TaggedItem.objects.get_by_model(Topic, tag),
    ),
    dict(title="Tribes",
        query=lambda tag: TaggedItem.objects.get_by_model(Tribe, tag),
    ),
    dict(title="Wiki Articles",
        query=lambda tag: TaggedItem.objects.get_by_model(WikiPage, tag),
    ),
)
tagging_ext_kwargs = {
    "tagged_models": tagged_models,
}

urlpatterns += patterns("",
    url(r"^tags/(?P<tag>.+)/(?P<model>.+)$", "tagging_ext.views.tag_by_model",
        kwargs=tagging_ext_kwargs, name="tagging_ext_tag_by_model"),
    url(r"^tags/(?P<tag>.+)/$", "tagging_ext.views.tag",
        kwargs=tagging_ext_kwargs, name="tagging_ext_tag"),
    url(r"^tags/$", "tagging_ext.views.index", name="tagging_ext_index"),
)

if settings.SERVE_MEDIA:
    urlpatterns += patterns("",
        url(r"", include("staticfiles.urls")),
    )

apps/chronicles/models.py
from django.core.urlresolvers import reverse
from django.contrib.auth.models import  User
from django.utils.translation import ugettext_lazy as _
from django.db import models

from groups.base import Group
from characters.models import Sheet

class Chronicle(Group):
    
    member_users = models.ManyToManyField(User, through='ChronicleMember', verbose_name=_('members'))

    private = models.BooleanField(_('private'), default=False)
    
    def get_absolute_url(self):
        return reverse('chronicle_detail', kwargs={'group_slug': self.slug})

    def member_queryset(self):
        return self.member_users.all()

    def user_is_member(self, user):
        return ChronicleMember.objects.filter(chronicle=self, user=user).count() > 0

    def get_url_kwargs(self):
        return {'chronicle_slug': self.slug}

    def get_sheets_for_user(self, user):
        if not self.user_is_member(user):
            return []

        cm = ChronicleMember.objects.get(user=user, chronicle=self)
        if 0 == cm.membership_role:
            return self.content_objects(Sheet)
        return self.content_objects(Sheet).filter(player=user)

class ChronicleMember(models.Model):
    chronicle = models.ForeignKey(Chronicle, related_name="members", verbose_name=_('chronicle'))
    user = models.ForeignKey(User, related_name='chronicles', verbose_name=_('user'))

    CHOICES = zip(range(5), ('storyteller', 'narrator', 'player', 'travelling_player', 'other'))
    membership_role = models.PositiveSmallIntegerField(choices=CHOICES, default=2)
    membership_role_other = models.CharField(default='', max_length=128)

apps/profiles/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from idios.models import ProfileBase


class Profile(ProfileBase):
    name = models.CharField(_("name"), max_length=50, null=True, blank=True)
    about = models.TextField(_("about"), null=True, blank=True)
    location = models.CharField(_("location"), max_length=40, null=True, blank=True)
    website = models.URLField(_("website"), null=True, blank=True, verify_exists=False)

templates/profiles/base.html
{% extends "site_base.html" %}

{% load i18n %}

{% block body_class %}profile{% endblock %}

{% block subnav %}
    {% if user.is_authenticated %}
        <ul>
            <li><a href="{% url profile_detail user.username %} ">{% trans "Your Profile" %}</a></li>
            <li><a href="{% url profile_list %} ">{% trans "All Profiles" %}</a></li>
        </ul>
    {% else %}
        &nbsp;
    {% endif %}
{% endblock %}

templates/profiles/profile.html
{% extends "profiles/base.html" %}

{% load i18n %}
{% load avatar_tags %}
{% load uni_form_tags %}
{% load group_tags %}
{% load blog_tags %}
{% load tagging_tags %}
{% load photo_tags %}
{% load threadedcommentstags %}

{% block head_title %}{% blocktrans %}Profile for {{ other_user }}{% endblocktrans %}{% endblock %}

{% block body %}
    
    <div class="right_panel">
        {% include "profiles/profile_right_panel.html" %}
    </div>
    
    <div class="left_panel">
        <div class="vcard">
            <div id="profile_avatar">
                <div><img src="{% avatar_url other_user 80 %}" alt="Photo of {{ other_user }}" class="photo" /></div>
                {% if is_me %}
                <a href="{% url avatar_change %}" id="avatar_replace">(replace)</a>
                {% endif %}
            </div>
            
            {% if other_user.get_profile.name %}
                <h1>{% blocktrans %}Profile for <span class="nickname">{{ other_user }}</span>{% endblocktrans %}</h1>
            {% else %}
                <h1>{% blocktrans %}Profile for <span class="fn nickname">{{ other_user }}</span>{% endblocktrans %}</h1>
            {% endif %}
            
            <div class="profile_info">
                {% if other_user.get_profile.name %}<p><b>{% trans "Name" %}</b>: <span class="fn">{{ other_user.get_profile.name }}</span></p>{% endif %}
                {% if other_user.get_profile.about %}<p><b>{% trans "About" %}</b>: {{ other_user.get_profile.about }}</p>{% endif %}
                {% if other_user.get_profile.location%}<p><b>{% trans "Location" %}</b>: {{ other_user.get_profile.location }}</p>{% endif %}
                {% if other_user.get_profile.website %}<p><b>{% trans "Website" %}</b>: <a class="url" href="{{ other_user.get_profile.website }}">{{ other_user.get_profile.website }}</a></p>{% endif %}
            </div>
            
            {% if is_me %}
                <p><a href="{% url profile_edit %}" rel="facebox">Edit profile</a></p>
            {% endif %}
            
            {% if user.is_authenticated %}
                {% if is_me %}
                {% else %}
                    {# @@@ this should be an inclusion tag #}
                    {% if is_friend %}
                        <p>{% blocktrans %}You are friends with {{ other_user }}.{% endblocktrans %} <a href="{% url messages_compose %}{{ other_user }}/">{% trans "Send a message" %}</a>.</p>
                        <div>
                            <form method="POST" action="">
                                <input type="hidden" name="action" value="remove" /><input type="submit" value="{% trans "remove from friends" %}"/>
                            </form>
                        </div>
                    {% else %}
                        {% if previous_invitations_from %}
                            <p>{% blocktrans %}{{ other_user }} has requested friendship.{% endblocktrans %}</p>
                            {% for invitation in previous_invitations_from %}
                                <div class="friendship_request">
                                    <p>From <a href="{% url profile_detail invitation.from_user.username %}">{{ invitation.from_user }}</a> ({{ invitation.sent }}):</p>
                                    <p class="invitation_message">{{ invitation.message }}</p>
                                    <form method="post" action="">
                                        <input type="hidden" name="invitation" value="{{ invitation.id }}"/>
                                        <input type="hidden" name="action" value="accept"/>
                                        <input type="submit" value="{% trans 'accept' %}" />
                                    </form>
                                    <form method="post" action="">
                                        <input type="hidden" name="invitation" value="{{ invitation.id }}"/>
                                        <input type="hidden" name="action" value="decline"/>
                                        <input type="submit" value="{% trans 'decline' %}" />
                                    </form>
                                </div>
                            {% endfor %}
                        {% else %}
                            {% if previous_invitations_to %}
                                <p>{% trans "Friendship request sent." %}</p>
                            {% else %}
                                <h2>{% trans "Add As Friend" %}</h2>
                                <form class="uniForm" method="POST" action="">
                                    <fieldset class="inlineLabels">
                                        {{ invite_form|as_uni_form }}
                                        <div class="form_block">
                                            <input type="hidden" name="action" value="invite" />
                                            <input type="submit" value="{% trans "invite" %}"/>
                                            {% blocktrans %}{{ other_user }} to be a friend.{%  endblocktrans %}
                                        </div>
                                    </fieldset>
                                </form>
                            {% endif %} {# previous_invitations_to #}
                        {% endif %} {# previous_invitations_from #}
                    {% endif %} {# is_friend #}
                    
                {% endif %} {# is me #}
                
                <h2>{% trans "Wiki Articles" %}</h2>
                
                {% if other_user.article_set.all %}
                    <table class="bookmarks">
                        {% for article in other_user.article_set.all %}
                        <tr class="{% cycle odd,even %}">
                            <td class="meta">
                                {{ article.created_at|date }}
                            </td>
                            <td>
                                <h2><a href="{% groupurl wiki_article article.group title=article.title %}">{{ article.title }}</a></h2>
                                <div class="body">{{ article.content|truncatewords:25 }}</div>
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    <p>{% trans "No wiki articles yet." %}</p>
                {% endif %}
                
                <h2>{% trans "Bookmarks" %}</h2>
                
                {% if other_user.saved_bookmarks.all %}
                    <table class="bookmarks narrow">
                        {% for bookmark_instance in other_user.saved_bookmarks.all.select_related %}
                            <tr class="{% cycle odd,even %} xfolkentry">
                                <td class="meta">
                                    {{ bookmark_instance.saved|date }}
                                    {# add who originally added it and when #}
                                </td>
                                <td>
                                    <h2><a class="taggedlink" href="{{ bookmark_instance.bookmark.url }}">{{ bookmark_instance.description }}</a></h2>
                                    <div class="url">{% if bookmark_instance.bookmark.get_favicon_url %}<img src="{{ bookmark_instance.bookmark.get_favicon_url }}" height="16" width="16"/> {% endif %}{{ bookmark_instance.bookmark.url }}</div>
                                    <div class="body description">{{ bookmark_instance.note|linebreaks }}</div>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    {% url add_bookmark as add_bookmark_url %}
                    <p>{% blocktrans %}You haven't added any <a href="{{ add_bookmark_url }}">bookmarks</a> yet.{% endblocktrans %}</p>
                {% endif %}
                
                
                <h2>{% trans "Blog Posts" %}</h2>
                
                {% if other_user.added_posts.all %}
                    {% for blog_post in other_user.added_posts.all %}
                        {% show_blog_post blog_post %}
                    {% endfor %}
                {% else %}
                    {% trans "No blog posts yet." %}
                {% endif %}
                
                <h2>{% trans "Photos" %}</h2>
                
                {% public_photos for other_user as photos %}
                
                {% if photos %}
                    <div class="clearfix">
                    {% for photo in photos %}
                        <div class="gallery-photo-thumb">
                            <a href="/photos/details/{{ photo.id }}/"><img src="{{ photo.get_thumbnail_url }}" alt="{{ photo.title }}"/></a>
                        </div>
                    {% endfor %}
                    </div>
                {% else %}
                   {% trans "No photos uploaded yet." %}
                {% endif %}
                
            {% else %} {# not user.is_authenticated #}
                {% url acct_signup as signup_url %}
                {% url acct_login as login_url %}
                <p>{% blocktrans %}<a href="{{ signup_url }}">Sign up</a> and <a href="{{ login_url }}">log in </a> to add this person as a friend and see their blog posts.{% endblocktrans %}</p>
            {% endif %}
        </div><!--/vcard-->
    </div>
{% endblock %}

{% block extra_body %}
    <script src="{{ STATIC_URL }}pinax/js/avatar.js" type="text/javascript"></script>
{% endblock %}

templates/profiles/profile_edit.html
{% extends "profiles/base.html" %}

{% load i18n %}

{% block head_title %}{% blocktrans %}Edit Profile{% endblocktrans %}{% endblock %}

{% block body %}
    
    <h1>{% trans "Edit Profile" %}</h1>
    
    {% include "profiles/profile_form.html" %}
    
{% endblock %}

templates/profiles/profile_edit_facebox.html
{% load i18n %}

<h1>{% trans "Edit Profile" %}</h1>

{% include "profiles/profile_form.html" %}

templates/profiles/profile_form.html
{% load uni_form_tags %}

<form class="uniForm" method="POST" action="{% url profile_edit %}">
{% csrf_token %}
    <fieldset>
        {{ profile_form|as_uni_form }}
        <div class="form_block">
            <input type="submit" value="update" />
            or <a href="{% url profile_detail profile.user.username %}">cancel</a>
        </div>
    </fieldset>
</form>

templates/profiles/profile_right_panel.html
{% load i18n %}
{% load avatar_tags %}

{% if is_me %}
    <div class="groups">
        <h2>{% trans "Your Chronicles" %}</h2>
        {% if other_user.chronicles.all %}
            {% for chronicle in other_user.chronicles.all %}
                <a href="{{ chronicle.chronicle.get_absolute_url }}">{{ chronicle.chronicle.name }}</a> -&gt; {{ chronicle.get_membership_role_display }}
            {% endfor %}
        {% else %}
            {% url chronicle_list as chronicle_url %}
            <p>{% blocktrans %}You are not yet a member of any <a href="{{ chronicle_url }}">chronicles</a>.{% endblocktrans %}</p>
        {% endif %}
    </div>
    <div class="friends">
        <h2>{% trans "Your Friends" %}</h2>
        {% if other_friends %}
            <table width="100%">
                {% for friendship in other_friends %}
                {% if forloop.counter0|divisibleby:"3" %}<tr>{% endif %}
                    <td>
                        <div class="avatar">{% avatar friendship.friend 40 %}</div>
                        <div class="details"><a href="{% url profile_detail friendship.friend.username %}" title="{{ friendship.friend.username }}">{{ friendship.friend.username }}</a></div>
                    </td>
                {% if forloop.counter0|add:"1"|divisibleby:"3" %}</tr>{% endif %}
                {% endfor %}
                {% if other_friends|length|divisibleby:"3" %}{% else %}</tr>{% endif %}
            </table>
        {% else %}
            <p>{% blocktrans %}None. You should look at the list of <a href="/profiles/">profiles</a> and see if there's anyone you know.{% endblocktrans %}</p>
        {% endif %}
    </div>
{% endif %}

{% if is_friend %}
    <div class="groups">
        <h2>{% blocktrans %}{{ other_user }}'s Chronicles{% endblocktrans %}</h2>
        {% if other_user.chronicles.all %}
            {% for chronicle in other_user.chronicles.all %}
                <a href="{{ chronicle.chronicle.get_absolute_url }}">{{ chronicle.chronicle.name }}</a> -&gt; {{ chronicle.get_membership_role_display }}
            {% endfor %}
        {% else %}
            {% url chronicle_list as chronicle_url %}
            <p>{% blocktrans %}Not yet a member of any <a href="{{ chronicle_url }}">chronicles</a>.{% endblocktrans %}</p>
        {% endif %}
    </div>
    <div class="friends">
        <h2>{% blocktrans %}{{ other_user }}'s Friends{% endblocktrans %}</h2>
        <table width="100%">
            {% for friendship in other_friends %}
                {% if forloop.counter0|divisibleby:"3" %}<tr>{% endif %}
                <td>
                    <div class="avatar">{% avatar friendship.friend 40 %}</div>
                    <div class="details"><a href="{% url profile_detail friendship.friend.username %}" title="{{ friendship.friend.username }}">{{ friendship.friend.username }}</a></div>
                </td>
                {% if forloop.counter0|add:"1"|divisibleby:"3" %}</tr>{% endif %}
            {% endfor %}
        {% if other_friends|length|divisibleby:"3" %}{% else %}</tr>{% endif %}
        </table>
    </div>
{% endif %}

templates/profiles/profiles.html
{% extends "profiles/base.html" %}

{% load i18n %}
{% load pagination_tags %}
{% load avatar_tags %}
{% load humanize %}
{% load profile_tags %}

{% block head_title %}{% blocktrans %}All Profiles{% endblocktrans %}{% endblock %}

{% block body %}
    <h1>{% trans "Profiles" %}</h1>
    
    <form method="GET" action="">
        <input type="text" name="search" value="{{ search_terms }}" />
        <input type="submit" value="Search" />
        {% if search_terms %}
            <a href="{% clear_search_url request %}">Clear Search Terms</a>
        {% endif %}
    </form>
    
    {% if users %}
        <p>{% trans "Order by:" %}
            {% ifequal order 'date' %}
                <a href="{% url profile_list %}?order=name">{% trans "Name" %} &uarr;</a>
            {% else %}
                <a href="{% url profile_list %}?order=date">{% trans "Date" %} &darr;</a>
            {% endifequal %}
        </p>
        
        {% autopaginate users%}
        
        {% ifequal order 'date'  %}
            {% regroup users by date_joined.date as users_by_date_joined %}
            
            {% for date in users_by_date_joined %}
                <h2 class="join_date">{{ date.grouper|naturalday:_("MONTH_DAY_FORMAT")|capfirst }}</h2>
                
                {% for user in date.list %}
                    {% show_profile user %}
                {% endfor %}
            {% endfor %}
        {% else %}
            {% for user in users %}
                {% show_profile user %}
            {% endfor %}
        {% endifequal %}
        
        {% paginate %}
        
       {% else %}
           <p>No profile were found.</p>
      {% endif %}
{% endblock %}